POI bubble start
Augmenters/FrontStone pull request #11
Opened 2023-10-15 21:56 UTC by ErikaJZhou

Basically creates a plane behind the test text that could be used as the backing for the POI info bubble. 
This isn't a finished bubble yet. It still needs to have the business info and rating added. Eventually, the info needs to be pulled from the API.
We may need to coordinate some frontend code organization and it seems Jules and Justin made some changes as well.
![Uploading grey-poi-bubble-start-10-15-23.PNG…]()

2023-10-27 20:49 UTC, ErikaJZhou commented
![poi-bubble-harpos-test](https://github.com/Augmenters/FrontStone/assets/55419983/9c46a835-9a94-498a-9874-7c2fe5eb00a3)
POI bubble test with info from the Harpo's mock data. Based on our Figma prototype. Still very rough but this version is likely what's going to be in the midterm demo video.

2023-10-29 20:00 UTC, ErikaJZhou commented
Address was removed from the POI bubble.

2023-10-29 20:05 UTC, jm564 requested changes

2023-10-29 20:05 UTC, jm564 commented on CityAssistant/CityAssistant/Views/CityARView.swift
> +//        let textFrameRect = CGRect(origin: rectOrigin, size: rectSize)
need to remove commented out code

2023-10-29 20:05 UTC, jm564 commented on CityAssistant/CityAssistant/Views/CityARView.swift
> +        let hours = "8 am to 9 pm"
Dont hardcode values, will make it more difficult to use this later

2023-10-29 20:05 UTC, jm564 commented on CityAssistant/CityAssistant/Views/CityARView.swift
> +        let businessNameText = create3dText(text: CameraView.mockPOI.BusinessName, x: -0.45, y: 0.4)
This should all be in its own function something like create bubble (POI)

2023-10-29 20:05 UTC, jm564 commented on CityAssistant/CityAssistant/Views/CityARView.swift
> +        let x = x
What is the point of x and y variables?

2023-10-29 21:08 UTC, ErikaJZhou commented on CityAssistant/CityAssistant/Views/CityARView.swift
> +        let x = x
Default values in case they're not provided, but specifies where the text appears

2023-10-29 21:08 UTC, ErikaJZhou commented on CityAssistant/CityAssistant/Views/CityARView.swift
> +        let businessNameText = create3dText(text: CameraView.mockPOI.BusinessName, x: -0.45, y: 0.4)
Moved to a new function createPOIBubble()

2023-11-06 02:35 UTC, ErikaJZhou commented
![IMG_532FFE8558CA-1](https://github.com/Augmenters/FrontStone/assets/55419983/eb609c92-a1aa-4999-bc44-71a7fd18d4cb)
@ABrain7710 and I worked on integrating @jm564 POI placement with bubble creation. Now the placePOI() function creates and places a POI. Using the newLocation to init the AnchorEntity caused the bubble to not show up.
Still has bug where bubble is not tappable.

2023-11-08 21:56 UTC, ErikaJZhou commented
The "refactor" branch was merged into this one.

2023-11-15 00:52 UTC, merged